version: "3.7"

services:
  db:
    image: postgres
    container_name: cwork_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=iagod
      - POSTGRES_PASSWORD=28974220
      - POSTGRES_DB=cwork
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: cwork_backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local